### ISSUE TITLE
formatting new list changed

### ISSUE THREAD

**Issue by rancer4** [waelisa/Best-blocklist#2]
you changed the format of the list from the old lists you used to have.  the old ones were in a 
HEADQUARTERS NATO RAPID DEPLOYABLE CORPS ITALY:2.112.19.56-2.112.19.63
now they are like
002.184.193.227 - 002.184.193.227 Detected AP2P on Dadehaye Donyaye Door proxy
my program i use peerblock, doesnt work with the new format.  i havent got a quick way to reformat it.  can you make an old format version or something for this?

**Comment by waelisa** [comment]
Fixed on 12.2
