### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by TonDevv** [waelisa/Best-blocklist#3]
how can i run it on ubuntu server ? could you help ?

**Comment by mlnl221** [comment]
if you are using qbitorrent
Download the .p2p file and save it somewhere in your config path

go to qbitorrent Options > Connection > IP Filtering, 

on File Path (.p2p) point it to the file you just downloaded. This will load all the ips from that file into your qbitorrent. 

Are you running a  q bitorrent docker image? you will have to mount the path from your ubuntu server and point it to your qbitorrent container. Drop the file in that container path then restart the container. 

In qbitorrent you will have to specify the file path as relative to the container.
